
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class Dialog extends javax.swing.JFrame {
    private String title;
    private String message;
    
    /**
     * Creates new form Dialog
     */
    public Dialog() {
        initComponents();
    }

    /**
     * Creates new form Dialog
     */
    public Dialog(String message) {
        initComponents();
        
        this.message = message;
        
    }
    
    public void setMessage(String message) {
        this.message = message;
        this.messageTxt.setText(message);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMessange = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        messageTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mensaje");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        popUpMessange.setBackground(java.awt.Color.white);
        popUpMessange.setOpaque(false);
        popUpMessange.setPreferredSize(new java.awt.Dimension(300, 163));
        popUpMessange.setLayout(new java.awt.BorderLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));

        okBtn.setBackground(new java.awt.Color(236, 0, 140));
        okBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        okBtn.setText("Ok");
        okBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        okBtn.setBorderPainted(false);
        okBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okBtn.setFocusPainted(false);
        okBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);

        messageTxt.setEditable(false);
        messageTxt.setColumns(20);
        messageTxt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        messageTxt.setRows(5);
        messageTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        scrollPane.setViewportView(messageTxt);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        popUpMessange.add(panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(popUpMessange, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea messageTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel popUpMessange;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
