
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class Dialog extends javax.swing.JFrame {
    private String title;
    private String message;
    
    /**
     * Creates new form Dialog
     */
    public Dialog() {
        initComponents();
    }

    /**
     * Creates new form Dialog
     */
    public Dialog(String message) {
        initComponents();
        
        this.message = message;
        
    }
    
    public void setMessage(String message) {
        this.message = message;
        this.messageTxt.setText(message);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMessange = new javax.swing.JPanel();
        messageTxt = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        popUpMessange.setOpaque(false);
        popUpMessange.setPreferredSize(new java.awt.Dimension(300, 100));

        messageTxt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        messageTxt.setPreferredSize(new java.awt.Dimension(250, 16));

        okBtn.setBackground(new java.awt.Color(236, 0, 140));
        okBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        okBtn.setText("Ok");
        okBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        okBtn.setBorderPainted(false);
        okBtn.setFocusPainted(false);
        okBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popUpMessangeLayout = new javax.swing.GroupLayout(popUpMessange);
        popUpMessange.setLayout(popUpMessangeLayout);
        popUpMessangeLayout.setHorizontalGroup(
            popUpMessangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpMessangeLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(messageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        popUpMessangeLayout.setVerticalGroup(
            popUpMessangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpMessangeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(popUpMessangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(popUpMessange, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel popUpMessange;
    // End of variables declaration//GEN-END:variables
}
