package view;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Random;
import java.util.Scanner;
import javax.swing.ImageIcon;
import model.structure.Files;
import model.system.Persona;

public class JoinView extends javax.swing.JFrame {

    File registro;

    /**
     * Creates new form Join
     */
    public JoinView() {
        initComponents();
        sos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        passLogin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        userSU = new javax.swing.JTextField();
        moneySU = new javax.swing.JTextField();
        lastNameSU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        nameSU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passSU = new javax.swing.JPasswordField();
        sos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Block Pain | Login");
        setIconImage((new ImageIcon(getClass().getResource("/resources/img/logo.png"))).getImage());
        setMinimumSize(new java.awt.Dimension(650, 500));

        mainPanel.setBackground(new java.awt.Color(27, 20, 100));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        tabbedPanel.setBackground(new java.awt.Color(236, 0, 140));
        tabbedPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabbedPanel.setFocusable(false);
        tabbedPanel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tabbedPanel.setMaximumSize(new java.awt.Dimension(500, 32767));
        tabbedPanel.setOpaque(true);
        tabbedPanel.setPreferredSize(new java.awt.Dimension(500, 353));
        tabbedPanel.setRequestFocusEnabled(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setFocusable(false);
        loginPanel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        userLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        userLogin.setToolTipText("Usuario");

        passLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        passLogin.setToolTipText("Contraseña");

        jButton1.setBackground(new java.awt.Color(0, 255, 197));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userLogin)
                        .addComponent(passLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Login", loginPanel);

        signUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpPanel.setFocusable(false);
        signUpPanel.setRequestFocusEnabled(false);
        signUpPanel.setLayout(null);

        userSU.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        userSU.setToolTipText("Usuario");
        signUpPanel.add(userSU);
        userSU.setBounds(209, 121, 177, 23);

        moneySU.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        moneySU.setToolTipText("Usuario");
        moneySU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneySUActionPerformed(evt);
            }
        });
        signUpPanel.add(moneySU);
        moneySU.setBounds(209, 221, 177, 23);
        moneySU.getAccessibleContext().setAccessibleDescription("Monto Inicial");

        lastNameSU.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lastNameSU.setToolTipText("Usuario");
        signUpPanel.add(lastNameSU);
        lastNameSU.setBounds(209, 69, 177, 23);
        lastNameSU.getAccessibleContext().setAccessibleDescription("Apellidos");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombres");
        signUpPanel.add(jLabel3);
        jLabel3.setBounds(53, 20, 74, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellidos");
        signUpPanel.add(jLabel4);
        jLabel4.setBounds(53, 72, 74, 17);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Monto Inicial");
        signUpPanel.add(jLabel5);
        jLabel5.setBounds(53, 221, 74, 23);

        signUpBtn.setBackground(new java.awt.Color(0, 255, 197));
        signUpBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        signUpBtn.setText("Registrar");
        signUpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signUpBtn.setBorderPainted(false);
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.setFocusPainted(false);
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        signUpPanel.add(signUpBtn);
        signUpBtn.setBounds(242, 278, 83, 21);

        nameSU.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameSU.setToolTipText("Usuario");
        signUpPanel.add(nameSU);
        nameSU.setBounds(209, 20, 177, 23);
        nameSU.getAccessibleContext().setAccessibleName("");
        nameSU.getAccessibleContext().setAccessibleDescription("Nombres");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Usuario");
        signUpPanel.add(jLabel6);
        jLabel6.setBounds(53, 124, 74, 17);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contraseña");
        signUpPanel.add(jLabel7);
        jLabel7.setBounds(53, 175, 74, 17);

        passSU.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        passSU.setToolTipText("Contraseña");
        signUpPanel.add(passSU);
        passSU.setBounds(209, 172, 177, 23);

        sos.setBackground(new java.awt.Color(255, 51, 51));
        sos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sos.setText("INVÁLIDO");
        sos.setAutoscrolls(true);
        sos.setEnabled(false);
        sos.setOpaque(true);
        signUpPanel.add(sos);
        sos.setBounds(390, 111, 99, 42);

        tabbedPanel.addTab("Sign Up", signUpPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        mainPanel.add(tabbedPanel, gridBagConstraints);
        tabbedPanel.getAccessibleContext().setAccessibleName("Form");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        Files f = new Files();
        registro = new File("C:\\Block-Pay\\registros.txt");
        f.searchOrCreateFile(registro, "registros.txt");
        
        int id = (int) Math.floor(Math.random()*(54321-1+1)+1);
        
        while (!f.searchInFile(registro,id)){
            id = (int) Math.floor(Math.random()*(54321-1+1)+1);
        }
        
        Persona p = new Persona(this.userSU.getText(), this.nameSU.getText(), this.lastNameSU.getText(), id, Float.parseFloat(this.moneySU.getText()));
        if (f.searchInFile(registro, p.getUserName())){
            f.writeFile(registro, p.getUserName(), p.getNames(), p.getLastNames(),
                p.getId(), p.getDinero());
        } else {
            sos.setVisible(true);
        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void moneySUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneySUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneySUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastNameSU;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField moneySU;
    private javax.swing.JTextField nameSU;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JPasswordField passSU;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel sos;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextField userLogin;
    private javax.swing.JTextField userSU;
    // End of variables declaration//GEN-END:variables
}
