package view;

import view.includes.Modal;
import controller.AccountController;
import model.system.Account;

/**
 *
 * @author sonya
 */
public class LoginView extends javax.swing.JFrame {

    private final AccountController accountController;
    
    /**
     * @param accountController
     */
    public LoginView(AccountController accountController) {
        this.accountController = accountController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginErrorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameErrorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordErrorPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        SignUpUsernameTxt = new javax.swing.JTextField();
        signUpPasswordTxt = new javax.swing.JTextField();
        loginUserLabel1 = new javax.swing.JLabel();
        loginUserLabel3 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        changeSaved = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        formZonePanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        loginFormPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginUserTxt = new javax.swing.JTextField();
        loginPasswordTxt = new javax.swing.JPasswordField();
        loginEnterBtn = new javax.swing.JButton();
        loginCreateAccountBtn = new javax.swing.JButton();
        imageZonePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        loginErrorPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginErrorPanel.setMaximumSize(new java.awt.Dimension(320, 95));
        loginErrorPanel.setMinimumSize(new java.awt.Dimension(320, 95));
        loginErrorPanel.setPreferredSize(new java.awt.Dimension(320, 95));
        loginErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña o usuario incorrectos :(");
        loginErrorPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        usernameErrorPanel.setBackground(new java.awt.Color(255, 255, 255));
        usernameErrorPanel.setMaximumSize(new java.awt.Dimension(320, 95));
        usernameErrorPanel.setMinimumSize(new java.awt.Dimension(320, 95));
        usernameErrorPanel.setPreferredSize(new java.awt.Dimension(320, 95));
        usernameErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Este nombre de usuario ya existe :(");
        usernameErrorPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        passwordErrorPanel.setBackground(new java.awt.Color(255, 255, 255));
        passwordErrorPanel.setMaximumSize(new java.awt.Dimension(252, 94));
        passwordErrorPanel.setMinimumSize(new java.awt.Dimension(252, 94));
        passwordErrorPanel.setPreferredSize(new java.awt.Dimension(252, 94));
        passwordErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("<html>La contraseña debe tener minimo 5 carácteres</html>");
        passwordErrorPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 40));

        signUpPanel.setBackground(new java.awt.Color(151, 58, 168));
        signUpPanel.setMaximumSize(new java.awt.Dimension(400, 300));
        signUpPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        signUpPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpUsernameTxt.setBackground(new java.awt.Color(87, 16, 137));
        SignUpUsernameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SignUpUsernameTxt.setForeground(new java.awt.Color(255, 194, 226));
        SignUpUsernameTxt.setToolTipText("Nombre de usuario");
        SignUpUsernameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 58, 168), 2, true));
        SignUpUsernameTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        SignUpUsernameTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        SignUpUsernameTxt.setName(""); // NOI18N
        SignUpUsernameTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        SignUpUsernameTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        signUpPanel.add(SignUpUsernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        signUpPasswordTxt.setBackground(new java.awt.Color(87, 16, 137));
        signUpPasswordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        signUpPasswordTxt.setForeground(new java.awt.Color(255, 194, 226));
        signUpPasswordTxt.setToolTipText("Nombre de usuario");
        signUpPasswordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 58, 168), 2, true));
        signUpPasswordTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        signUpPasswordTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        signUpPasswordTxt.setName(""); // NOI18N
        signUpPasswordTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        signUpPasswordTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        signUpPanel.add(signUpPasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        loginUserLabel1.setBackground(new java.awt.Color(30, 27, 24));
        loginUserLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel1.setText("Usuario");
        signUpPanel.add(loginUserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        loginUserLabel3.setBackground(new java.awt.Color(30, 27, 24));
        loginUserLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel3.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel3.setText("Contraseña");
        signUpPanel.add(loginUserLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        signUpBtn.setBackground(new java.awt.Color(234, 105, 139));
        signUpBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn.setText("Confirmar");
        signUpBtn.setToolTipText("Ingresar");
        signUpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 250, 255), 1, true));
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.setFocusPainted(false);
        signUpBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        signUpBtn.setMaximumSize(new java.awt.Dimension(70, 35));
        signUpBtn.setMinimumSize(new java.awt.Dimension(70, 35));
        signUpBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        signUpPanel.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 89, -1));

        changeSaved.setBackground(new java.awt.Color(255, 255, 255));
        changeSaved.setMaximumSize(new java.awt.Dimension(320, 95));
        changeSaved.setMinimumSize(new java.awt.Dimension(320, 95));
        changeSaved.setPreferredSize(new java.awt.Dimension(320, 95));
        changeSaved.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña o usuario incorrectos :(");
        changeSaved.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bock Pay | Login");
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(880, 525));
        setName("Login"); // NOI18N
        setSize(new java.awt.Dimension(880, 525));

        formZonePanel.setBackground(new java.awt.Color(71, 18, 107));
        formZonePanel.setMaximumSize(new java.awt.Dimension(500, 32767));
        formZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        formZonePanel.setPreferredSize(new java.awt.Dimension(400, 500));
        formZonePanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(27, 20, 100));
        formPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        formPanel.setOpaque(false);
        formPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        formPanel.setLayout(new java.awt.BorderLayout());

        loginFormPanel.setBackground(new java.awt.Color(71, 18, 107));
        loginFormPanel.setOpaque(false);
        loginFormPanel.setLayout(new java.awt.GridBagLayout());

        loginUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserLabel, gridBagConstraints);

        loginPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordLabel, gridBagConstraints);

        loginUserTxt.setBackground(new java.awt.Color(151, 58, 168));
        loginUserTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginUserTxt.setToolTipText("Nombre de usuario");
        loginUserTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 18, 107), 2, true));
        loginUserTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginUserTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginUserTxt.setName(""); // NOI18N
        loginUserTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginUserTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        loginUserTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserTxt, gridBagConstraints);

        loginPasswordTxt.setBackground(new java.awt.Color(151, 58, 168));
        loginPasswordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordTxt.setToolTipText("Contreña");
        loginPasswordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 18, 107), 2, true));
        loginPasswordTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginPasswordTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginPasswordTxt.setMinimumSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordTxt, gridBagConstraints);

        loginEnterBtn.setBackground(new java.awt.Color(234, 105, 139));
        loginEnterBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginEnterBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginEnterBtn.setText("Ingresar");
        loginEnterBtn.setToolTipText("Ingresar");
        loginEnterBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 138, 178), 1, true));
        loginEnterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginEnterBtn.setFocusPainted(false);
        loginEnterBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        loginEnterBtn.setMaximumSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.setMinimumSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEnterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginEnterBtn, gridBagConstraints);

        loginCreateAccountBtn.setBackground(new java.awt.Color(27, 20, 100));
        loginCreateAccountBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        loginCreateAccountBtn.setForeground(new java.awt.Color(255, 209, 102));
        loginCreateAccountBtn.setText("Crear cuenta");
        loginCreateAccountBtn.setToolTipText("Crear una cuenta");
        loginCreateAccountBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 16, 4, 16));
        loginCreateAccountBtn.setBorderPainted(false);
        loginCreateAccountBtn.setContentAreaFilled(false);
        loginCreateAccountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginCreateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCreateAccountBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        loginFormPanel.add(loginCreateAccountBtn, gridBagConstraints);

        formPanel.add(loginFormPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        formZonePanel.add(formPanel, gridBagConstraints);

        getContentPane().add(formZonePanel, java.awt.BorderLayout.WEST);

        imageZonePanel.setBackground(new java.awt.Color(255, 255, 255));
        imageZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        imageZonePanel.setPreferredSize(new java.awt.Dimension(400, 400));
        imageZonePanel.setLayout(new java.awt.GridBagLayout());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        imageZonePanel.add(imageLabel, new java.awt.GridBagConstraints());

        getContentPane().add(imageZonePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEnterBtnActionPerformed
        String username = loginUserTxt.getText().trim();
        String password = loginPasswordTxt.getText();
        
        if (accountController.verifyPassword(username, password)) {
            this.setVisible(false);
            MainView mainView = new MainView(accountController.getAccount(username), accountController);
            mainView.setVisible(true);
        } else {
            Modal modal = new Modal(this, "Error login", true, loginErrorPanel);
        }
    }//GEN-LAST:event_loginEnterBtnActionPerformed

    private void loginCreateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCreateAccountBtnActionPerformed
        String username = loginUserTxt.getText().trim();
        String password = loginPasswordTxt.getText().trim();
        
        SignUpUsernameTxt.setText(username);
        signUpPasswordTxt.setText(password);
        
        Modal modal = new Modal(this, "Registrarse", true, signUpPanel);
        
    }//GEN-LAST:event_loginCreateAccountBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        String username = SignUpUsernameTxt.getText().trim();
        String password = signUpPasswordTxt.getText().trim();
        
        if (password.length() < 5) {
            Modal modal = new Modal(this, "Error contraseña", true, passwordErrorPanel);
        } else {
            if (accountController.verifyUsername(username)) {
                Account account = new Account(10, username, password);
                
                accountController.addAccount(account);
                this.setVisible(false);
                MainView mainView = new MainView(account, accountController);
                mainView.setVisible(true);
                
            } else {
                Modal modal = new Modal(this, "Nombre ya existe", true, usernameErrorPanel);
            }
        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void loginUserTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SignUpUsernameTxt;
    private javax.swing.JPanel changeSaved;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formZonePanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imageZonePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginCreateAccountBtn;
    private javax.swing.JButton loginEnterBtn;
    private javax.swing.JPanel loginErrorPanel;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPasswordField loginPasswordTxt;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JLabel loginUserLabel1;
    private javax.swing.JLabel loginUserLabel3;
    private javax.swing.JTextField loginUserTxt;
    private javax.swing.JPanel passwordErrorPanel;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JTextField signUpPasswordTxt;
    private javax.swing.JPanel usernameErrorPanel;
    // End of variables declaration//GEN-END:variables

}
