package view;

import view.includes.Modal;
import controller.AccountController;
import model.system.Account;

/**
 *
 * @author sonya
 */
public class LoginView extends javax.swing.JFrame {

    private final AccountController accountController;
    
    /**
     * @param accountController
     */
    public LoginView(AccountController accountController) {
        this.accountController = accountController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginErrorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameErrorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordErrorPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        userTxt = new javax.swing.JTextField();
        loginUserTxt3 = new javax.swing.JTextField();
        loginUserLabel1 = new javax.swing.JLabel();
        loginUserLabel2 = new javax.swing.JLabel();
        loginUserLabel3 = new javax.swing.JLabel();
        confirmationBtn = new javax.swing.JButton();
        formZonePanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        loginFormPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginUserTxt = new javax.swing.JTextField();
        loginPasswordTxt = new javax.swing.JPasswordField();
        loginEnterBtn = new javax.swing.JButton();
        loginCreateAccountBtn = new javax.swing.JButton();
        imageZonePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        loginErrorPanel.setBackground(new java.awt.Color(27, 20, 100));
        loginErrorPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        loginErrorPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        loginErrorPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        loginErrorPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        loginErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña o usuario incorrectos");
        loginErrorPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        usernameErrorPanel.setBackground(new java.awt.Color(27, 20, 100));
        usernameErrorPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        usernameErrorPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        usernameErrorPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        usernameErrorPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        usernameErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Este nombre de usuario ya existe");
        usernameErrorPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        passwordErrorPanel.setBackground(new java.awt.Color(27, 20, 100));
        passwordErrorPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        passwordErrorPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        passwordErrorPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        passwordErrorPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        passwordErrorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>La contraseña debe tener minimo 5 carácteres</html>");
        passwordErrorPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 40));

        signUpPanel.setBackground(new java.awt.Color(27, 20, 100));
        signUpPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        signUpPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        signUpPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        signUpPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt.setBackground(new java.awt.Color(53, 42, 157));
        nameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nameTxt.setToolTipText("Nombre de usuario");
        nameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        nameTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        nameTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        nameTxt.setName(""); // NOI18N
        nameTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        nameTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        signUpPanel.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 116, -1, -1));

        userTxt.setBackground(new java.awt.Color(53, 42, 157));
        userTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 255, 255));
        userTxt.setToolTipText("Nombre de usuario");
        userTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        userTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        userTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        userTxt.setName(""); // NOI18N
        userTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        userTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        signUpPanel.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 65, -1, -1));

        loginUserTxt3.setBackground(new java.awt.Color(53, 42, 157));
        loginUserTxt3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserTxt3.setForeground(new java.awt.Color(255, 255, 255));
        loginUserTxt3.setToolTipText("Nombre de usuario");
        loginUserTxt3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        loginUserTxt3.setCaretColor(new java.awt.Color(236, 0, 140));
        loginUserTxt3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginUserTxt3.setName(""); // NOI18N
        loginUserTxt3.setPreferredSize(new java.awt.Dimension(170, 33));
        loginUserTxt3.setSelectionColor(new java.awt.Color(236, 0, 140));
        signUpPanel.add(loginUserTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 167, -1, -1));

        loginUserLabel1.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel1.setText("Usuario");
        signUpPanel.add(loginUserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 121, -1, -1));

        loginUserLabel2.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel2.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel2.setText("Nombre");
        signUpPanel.add(loginUserLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 70, -1, -1));

        loginUserLabel3.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel3.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel3.setText("Contraseña");
        signUpPanel.add(loginUserLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 167, -1, -1));

        confirmationBtn.setBackground(new java.awt.Color(236, 0, 140));
        confirmationBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        confirmationBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmationBtn.setText("Confirmar");
        confirmationBtn.setToolTipText("Ingresar");
        confirmationBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        confirmationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmationBtn.setFocusPainted(false);
        confirmationBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        confirmationBtn.setMaximumSize(new java.awt.Dimension(70, 35));
        confirmationBtn.setMinimumSize(new java.awt.Dimension(70, 35));
        confirmationBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        confirmationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationBtnActionPerformed(evt);
            }
        });
        signUpPanel.add(confirmationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 218, 89, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bock Pay | Login");
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(880, 525));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(880, 525));

        formZonePanel.setBackground(new java.awt.Color(27, 20, 100));
        formZonePanel.setMaximumSize(new java.awt.Dimension(500, 32767));
        formZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        formZonePanel.setPreferredSize(new java.awt.Dimension(400, 500));
        formZonePanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(27, 20, 100));
        formPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        formPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        formPanel.setLayout(new java.awt.BorderLayout());

        loginFormPanel.setBackground(new java.awt.Color(27, 20, 100));
        loginFormPanel.setLayout(new java.awt.GridBagLayout());

        loginUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserLabel, gridBagConstraints);

        loginPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordLabel, gridBagConstraints);

        loginUserTxt.setBackground(new java.awt.Color(53, 42, 157));
        loginUserTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginUserTxt.setToolTipText("Nombre de usuario");
        loginUserTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        loginUserTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginUserTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginUserTxt.setName(""); // NOI18N
        loginUserTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginUserTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserTxt, gridBagConstraints);

        loginPasswordTxt.setBackground(new java.awt.Color(53, 42, 157));
        loginPasswordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordTxt.setToolTipText("Contreña");
        loginPasswordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        loginPasswordTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginPasswordTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginPasswordTxt.setMinimumSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordTxt, gridBagConstraints);

        loginEnterBtn.setBackground(new java.awt.Color(236, 0, 140));
        loginEnterBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginEnterBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginEnterBtn.setText("Ingresar");
        loginEnterBtn.setToolTipText("Ingresar");
        loginEnterBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        loginEnterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginEnterBtn.setFocusPainted(false);
        loginEnterBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        loginEnterBtn.setMaximumSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.setMinimumSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        loginEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEnterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginEnterBtn, gridBagConstraints);

        loginCreateAccountBtn.setBackground(new java.awt.Color(27, 20, 100));
        loginCreateAccountBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginCreateAccountBtn.setForeground(new java.awt.Color(236, 0, 140));
        loginCreateAccountBtn.setText("Crear cuenta");
        loginCreateAccountBtn.setToolTipText("Crear una cuenta");
        loginCreateAccountBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 16, 4, 16));
        loginCreateAccountBtn.setBorderPainted(false);
        loginCreateAccountBtn.setContentAreaFilled(false);
        loginCreateAccountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginCreateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCreateAccountBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        loginFormPanel.add(loginCreateAccountBtn, gridBagConstraints);

        formPanel.add(loginFormPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        formZonePanel.add(formPanel, gridBagConstraints);

        getContentPane().add(formZonePanel, java.awt.BorderLayout.WEST);

        imageZonePanel.setBackground(new java.awt.Color(255, 255, 255));
        imageZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        imageZonePanel.setPreferredSize(new java.awt.Dimension(400, 400));
        imageZonePanel.setLayout(new java.awt.GridBagLayout());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        imageZonePanel.add(imageLabel, new java.awt.GridBagConstraints());

        getContentPane().add(imageZonePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEnterBtnActionPerformed
        String username = loginUserTxt.getText();
        String password = loginPasswordTxt.getText();
        
        if (accountController.verifyPassword(username, password)) {
            this.setVisible(false);
            MainView mainView = new MainView(accountController.getAccount(username), accountController);
            mainView.setVisible(true);
        } else {
            Modal modal = new Modal(this, "Error login", true, loginErrorPanel);
        }
    }//GEN-LAST:event_loginEnterBtnActionPerformed

    private void loginCreateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCreateAccountBtnActionPerformed
        String username = loginUserTxt.getText();
        String password = loginPasswordTxt.getText().trim();
        
        if (password.length() < 5) {
            Modal modal = new Modal(this, "Error contraseña", true, passwordErrorPanel);
            
        } else {
            if (accountController.verifyUsername(username)) {
                Account account = new Account(0, username, password);
                accountController.addAccount(account);
                
                this.setVisible(false);
                MainView mainView = new MainView(accountController.getAccount(username), accountController);
                mainView.setVisible(true);
            } else {
                Modal modal = new Modal(this, "Error nombre de usuario", true, usernameErrorPanel);
            }
        }
    }//GEN-LAST:event_loginCreateAccountBtnActionPerformed

    private void confirmationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationBtnActionPerformed
    
    }//GEN-LAST:event_confirmationBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmationBtn;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formZonePanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imageZonePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginCreateAccountBtn;
    private javax.swing.JButton loginEnterBtn;
    private javax.swing.JPanel loginErrorPanel;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPasswordField loginPasswordTxt;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JLabel loginUserLabel1;
    private javax.swing.JLabel loginUserLabel2;
    private javax.swing.JLabel loginUserLabel3;
    private javax.swing.JTextField loginUserTxt;
    private javax.swing.JTextField loginUserTxt3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPanel passwordErrorPanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JTextField userTxt;
    private javax.swing.JPanel usernameErrorPanel;
    // End of variables declaration//GEN-END:variables

}
