package view;

import model.system.Account;

/**
 *
 * @author sonya
 */
public class LoginView extends javax.swing.JFrame {

    /** Creates new form t */
    public LoginView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formZonePanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        loginFormPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginUserTxt = new javax.swing.JTextField();
        loginPasswordTxt = new javax.swing.JPasswordField();
        loginEnterBtn = new javax.swing.JButton();
        loginCreateAccountBtn = new javax.swing.JButton();
        imageZonePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bock Pay | Login");
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(880, 505));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 505));
        setResizable(false);
        setSize(new java.awt.Dimension(880, 505));

        formZonePanel.setBackground(new java.awt.Color(27, 20, 100));
        formZonePanel.setMaximumSize(new java.awt.Dimension(500, 32767));
        formZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        formZonePanel.setPreferredSize(new java.awt.Dimension(400, 500));
        formZonePanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(27, 20, 100));
        formPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        formPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        formPanel.setLayout(new java.awt.BorderLayout());

        loginFormPanel.setBackground(new java.awt.Color(27, 20, 100));
        loginFormPanel.setLayout(new java.awt.GridBagLayout());

        loginUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUserLabel.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserLabel, gridBagConstraints);

        loginPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordLabel, gridBagConstraints);

        loginUserTxt.setBackground(new java.awt.Color(53, 42, 157));
        loginUserTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginUserTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginUserTxt.setToolTipText("Nombre de usuario");
        loginUserTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        loginUserTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginUserTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginUserTxt.setName(""); // NOI18N
        loginUserTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginUserTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginUserTxt, gridBagConstraints);

        loginPasswordTxt.setBackground(new java.awt.Color(53, 42, 157));
        loginPasswordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginPasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordTxt.setToolTipText("Contreña");
        loginPasswordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        loginPasswordTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        loginPasswordTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        loginPasswordTxt.setMinimumSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        loginPasswordTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginPasswordTxt, gridBagConstraints);

        loginEnterBtn.setBackground(new java.awt.Color(236, 0, 140));
        loginEnterBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginEnterBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginEnterBtn.setText("Ingresar");
        loginEnterBtn.setToolTipText("Ingresar");
        loginEnterBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 5, true));
        loginEnterBtn.setBorderPainted(false);
        loginEnterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginEnterBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        loginEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEnterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginEnterBtn, gridBagConstraints);

        loginCreateAccountBtn.setBackground(new java.awt.Color(27, 20, 100));
        loginCreateAccountBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loginCreateAccountBtn.setForeground(new java.awt.Color(236, 0, 140));
        loginCreateAccountBtn.setText("Crear cuenta");
        loginCreateAccountBtn.setToolTipText("Crear una cuenta");
        loginCreateAccountBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 16, 4, 16));
        loginCreateAccountBtn.setBorderPainted(false);
        loginCreateAccountBtn.setContentAreaFilled(false);
        loginCreateAccountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginCreateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCreateAccountBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        loginFormPanel.add(loginCreateAccountBtn, gridBagConstraints);

        formPanel.add(loginFormPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        formZonePanel.add(formPanel, gridBagConstraints);

        getContentPane().add(formZonePanel, java.awt.BorderLayout.WEST);

        imageZonePanel.setBackground(new java.awt.Color(255, 255, 255));
        imageZonePanel.setMinimumSize(new java.awt.Dimension(400, 0));
        imageZonePanel.setPreferredSize(new java.awt.Dimension(400, 400));
        imageZonePanel.setLayout(new java.awt.GridBagLayout());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        imageZonePanel.add(imageLabel, new java.awt.GridBagConstraints());

        getContentPane().add(imageZonePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEnterBtnActionPerformed
        // LOGIN
        Account account = null; // DO-TO CODE HERE

        if (account == null) {

        } else {
            this.setVisible(false);
            MainView mainView = new MainView(account);
            mainView.setVisible(true);
        }
    }//GEN-LAST:event_loginEnterBtnActionPerformed

    private void loginCreateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCreateAccountBtnActionPerformed
        // CREATE AND ACCOUNT
        Account account = null; // DO-TO CODE HERE

        if (account == null) {
            this.setVisible(false);
            MainView mainView = new MainView(account);
            mainView.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_loginCreateAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formZonePanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imageZonePanel;
    private javax.swing.JButton loginCreateAccountBtn;
    private javax.swing.JButton loginEnterBtn;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPasswordField loginPasswordTxt;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JTextField loginUserTxt;
    // End of variables declaration//GEN-END:variables

}
