package view;

import model.structure.Arbol;
import controller.TransaccionController;

public class MainView extends javax.swing.JFrame {
    private final Arbol arbol;
    private final ArbolGrafico arbolGrafico;
    private final TransaccionController transaccionController;

    public MainView(Arbol arbol) {
        this.transaccionController = new TransaccionController(arbol);
        this.arbol = arbol;
        this.arbolGrafico = new ArbolGrafico(arbol);

        initComponents();
        this.arbolPanel.add(this.arbolGrafico);
        this.mainPanel.add(this.inicioPanel);
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioPanel = new javax.swing.JPanel();
        arbolPanel = new javax.swing.JPanel();
        perfilPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        ActivityPanel = new javax.swing.JPanel();
        showArbolBtn = new javax.swing.JButton();
        showInicioBtn = new javax.swing.JButton();
        showPerfilBtn = new javax.swing.JButton();

        inicioPanel.setLayout(new java.awt.BorderLayout());

        arbolPanel.setLayout(new java.awt.BorderLayout());

        perfilPanel.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        showArbolBtn.setText("Arbol");
        showArbolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showArbolBtnActionPerformed(evt);
            }
        });
        ActivityPanel.add(showArbolBtn);

        showInicioBtn.setText("Inicio");
        showInicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInicioBtnActionPerformed(evt);
            }
        });
        ActivityPanel.add(showInicioBtn);

        showPerfilBtn.setText("Perfil");
        showPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPerfilBtnActionPerformed(evt);
            }
        });
        ActivityPanel.add(showPerfilBtn);

        getContentPane().add(ActivityPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showArbolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showArbolBtnActionPerformed
        this.mainPanel.removeAll();
        this.mainPanel.add(this.arbolPanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_showArbolBtnActionPerformed

    private void showInicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInicioBtnActionPerformed
        this.mainPanel.removeAll();
        this.mainPanel.add(this.inicioPanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_showInicioBtnActionPerformed

    private void showPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPerfilBtnActionPerformed
        this.mainPanel.removeAll();
        this.mainPanel.add(this.perfilPanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_showPerfilBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivityPanel;
    private javax.swing.JPanel arbolPanel;
    private javax.swing.JPanel inicioPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel perfilPanel;
    private javax.swing.JButton showArbolBtn;
    private javax.swing.JButton showInicioBtn;
    private javax.swing.JButton showPerfilBtn;
    // End of variables declaration//GEN-END:variables
}
