package view;

/**
 *
 * @author sonya
 */
public class WelcomeView extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public WelcomeView() {
        initComponents();
    }

    public void setMaxValue(int max) {
        this.progressBar.setMaximum(max);
    }
    
    public void progress() {
        this.progressBar.setValue(this.progressBar.getValue() + 1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPael = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rohi Coins | Werlcome");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        mainPael.setBackground(new java.awt.Color(17, 32, 49));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 179, 68));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROCHI-COINS");

        jLabel2.setBackground(new java.awt.Color(255, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGO");

        javax.swing.GroupLayout mainPaelLayout = new javax.swing.GroupLayout(mainPael);
        mainPael.setLayout(mainPaelLayout);
        mainPaelLayout.setHorizontalGroup(
            mainPaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(mainPaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        mainPaelLayout.setVerticalGroup(
            mainPaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        getContentPane().add(mainPael, java.awt.BorderLayout.CENTER);

        footerPanel.setBackground(new java.awt.Color(17, 32, 49));

        progressBar.setBackground(new java.awt.Color(212, 236, 221));
        progressBar.setForeground(new java.awt.Color(224, 93, 93));
        progressBar.setValue(50);
        progressBar.setBorderPainted(false);
        progressBar.setOpaque(true);
        progressBar.setPreferredSize(new java.awt.Dimension(300, 14));
        progressBar.setStringPainted(true);
        footerPanel.add(progressBar);

        getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPael;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
