
package view.includes;

import java.awt.Component;
import javax.swing.JPanel;

public class modal extends javax.swing.JPanel {

    private final JPanel parent;
    
    public modal(JPanel parent, String title) {
        initComponents();
        this.parent = parent;
        this.titleLabel.setText(title);
    }

    public modal(JPanel parent, String title, Component component) {
        initComponents();
        this.parent = parent;
        this.titleLabel.setText(title);
        this.bodyPanel.add(component);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        x = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(27, 20, 100));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 3, true));
        headerPanel.setPreferredSize(new java.awt.Dimension(262, 30));
        headerPanel.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Title");
        titleLabel.setMaximumSize(new java.awt.Dimension(250, 17));
        titleLabel.setMinimumSize(new java.awt.Dimension(200, 17));
        titleLabel.setPreferredSize(new java.awt.Dimension(200, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        headerPanel.add(titleLabel, gridBagConstraints);

        x.setBackground(new java.awt.Color(236, 0, 140));
        x.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setText("x");
        x.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 2, true));
        x.setContentAreaFilled(false);
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.setMaximumSize(new java.awt.Dimension(20, 20));
        x.setMinimumSize(new java.awt.Dimension(20, 20));
        x.setPreferredSize(new java.awt.Dimension(20, 20));
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        headerPanel.add(x, gridBagConstraints);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setMaximumSize(new java.awt.Dimension(300, 350));
        bodyPanel.setMinimumSize(new java.awt.Dimension(300, 198));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton x;
    // End of variables declaration//GEN-END:variables
}
