/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.includes;

import model.system.Transaction;

/**
 *
 * @author 57301
 */
public class TransactionCard extends javax.swing.JPanel {
    
private final Transaction transaction;
    /**
     * Creates new form TransactionCard
     * @param transaction
     */
    public TransactionCard(Transaction transaction) {
        this.transaction = transaction;
        initComponents();
        
        loadData();
    }
    
     private void loadData(){
        remitentIdTxt.setText(transaction.getRemitent().getID());
        destinataryIdTxt.setText(transaction.getDestinatary().getID());
        moneyTxt.setText(transaction.getMoney()+"");
        dateTxt.setText(transaction.getDate()+"");
        messageTxt.setText(transaction.getMessange());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        remitentIdTxt = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        nicknameLabel4 = new javax.swing.JLabel();
        destinataryIdTxt = new javax.swing.JTextField();
        nicknameLabel5 = new javax.swing.JLabel();
        moneyTxt = new javax.swing.JTextField();
        nicknameLabel6 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        nicknameLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxt = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(430, 535));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSeparator4, gridBagConstraints);

        remitentIdTxt.setEditable(false);
        remitentIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        remitentIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remitentIdTxt.setForeground(new java.awt.Color(27, 20, 100));
        remitentIdTxt.setToolTipText("Id billetera remitente");
        remitentIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        remitentIdTxt.setMaximumSize(new java.awt.Dimension(150, 30));
        remitentIdTxt.setMinimumSize(new java.awt.Dimension(150, 30));
        remitentIdTxt.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(remitentIdTxt, gridBagConstraints);

        nicknameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel.setText("Remitente ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nicknameLabel, gridBagConstraints);

        nicknameLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel4.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel4.setText("Destinatario ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nicknameLabel4, gridBagConstraints);

        destinataryIdTxt.setEditable(false);
        destinataryIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        destinataryIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        destinataryIdTxt.setForeground(new java.awt.Color(27, 20, 100));
        destinataryIdTxt.setToolTipText("Id billetera destinatario");
        destinataryIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        destinataryIdTxt.setMaximumSize(new java.awt.Dimension(150, 30));
        destinataryIdTxt.setMinimumSize(new java.awt.Dimension(150, 30));
        destinataryIdTxt.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(destinataryIdTxt, gridBagConstraints);

        nicknameLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel5.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel5.setText("Dinero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nicknameLabel5, gridBagConstraints);

        moneyTxt.setEditable(false);
        moneyTxt.setBackground(new java.awt.Color(255, 255, 255));
        moneyTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        moneyTxt.setForeground(new java.awt.Color(27, 20, 100));
        moneyTxt.setToolTipText("Dinero enviado");
        moneyTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        moneyTxt.setMaximumSize(new java.awt.Dimension(150, 30));
        moneyTxt.setMinimumSize(new java.awt.Dimension(150, 30));
        moneyTxt.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(moneyTxt, gridBagConstraints);

        nicknameLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel6.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel6.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nicknameLabel6, gridBagConstraints);

        dateTxt.setEditable(false);
        dateTxt.setBackground(new java.awt.Color(255, 255, 255));
        dateTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(27, 20, 100));
        dateTxt.setToolTipText("Fecha");
        dateTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        dateTxt.setMaximumSize(new java.awt.Dimension(150, 30));
        dateTxt.setMinimumSize(new java.awt.Dimension(150, 30));
        dateTxt.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(dateTxt, gridBagConstraints);

        nicknameLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel7.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel7.setText("Mensaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nicknameLabel7, gridBagConstraints);

        messageTxt.setEditable(false);
        messageTxt.setColumns(20);
        messageTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        messageTxt.setForeground(new java.awt.Color(27, 20, 100));
        messageTxt.setRows(5);
        messageTxt.setToolTipText("Mensaje");
        messageTxt.setWrapStyleWord(true);
        messageTxt.setMinimumSize(new java.awt.Dimension(164, 94));
        messageTxt.setPreferredSize(new java.awt.Dimension(240, 105));
        messageTxt.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(messageTxt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField destinataryIdTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea messageTxt;
    private javax.swing.JTextField moneyTxt;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel nicknameLabel4;
    private javax.swing.JLabel nicknameLabel5;
    private javax.swing.JLabel nicknameLabel6;
    private javax.swing.JLabel nicknameLabel7;
    private javax.swing.JTextField remitentIdTxt;
    // End of variables declaration//GEN-END:variables
}
