/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.includes;

import model.system.Transaction;

/**
 *
 * @author 57301
 */
public class TransactionCard extends javax.swing.JPanel {
    
private final Transaction transaction;
    /**
     * Creates new form TransactionCard
     * @param transaction
     */
    public TransactionCard(Transaction transaction) {
        this.transaction = transaction;
        initComponents();
        
        loadData();
    }
    
     private void loadData(){
        remitentIdTxt.setText(transaction.getRemitent().getID());
        destinataryIdTxt.setText(transaction.getDestinatary().getID());
        moneyTxt.setText(transaction.getMoney()+"");
        dateTxt.setText(transaction.getDate()+"");
        messageTxt.setText(transaction.getMessange());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        remitentIdTxt = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        nicknameLabel4 = new javax.swing.JLabel();
        destinataryIdTxt = new javax.swing.JTextField();
        nicknameLabel5 = new javax.swing.JLabel();
        moneyTxt = new javax.swing.JTextField();
        nicknameLabel6 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        nicknameLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxt = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(430, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(430, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 530));

        remitentIdTxt.setEditable(false);
        remitentIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        remitentIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remitentIdTxt.setForeground(new java.awt.Color(27, 20, 100));
        remitentIdTxt.setToolTipText("Id billetera remitente");
        remitentIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        remitentIdTxt.setMinimumSize(new java.awt.Dimension(60, 32));
        remitentIdTxt.setPreferredSize(new java.awt.Dimension(60, 32));

        nicknameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel.setText("Remitente ID");

        nicknameLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel4.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel4.setText("Destinatario ID");

        destinataryIdTxt.setEditable(false);
        destinataryIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        destinataryIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        destinataryIdTxt.setForeground(new java.awt.Color(27, 20, 100));
        destinataryIdTxt.setToolTipText("Id billetera destinatario");
        destinataryIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        destinataryIdTxt.setMinimumSize(new java.awt.Dimension(60, 32));
        destinataryIdTxt.setPreferredSize(new java.awt.Dimension(60, 32));

        nicknameLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel5.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel5.setText("Dinero");

        moneyTxt.setEditable(false);
        moneyTxt.setBackground(new java.awt.Color(255, 255, 255));
        moneyTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        moneyTxt.setForeground(new java.awt.Color(27, 20, 100));
        moneyTxt.setToolTipText("Dinero enviado");
        moneyTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        moneyTxt.setMinimumSize(new java.awt.Dimension(60, 32));
        moneyTxt.setPreferredSize(new java.awt.Dimension(60, 32));

        nicknameLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel6.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel6.setText("Fecha");

        dateTxt.setEditable(false);
        dateTxt.setBackground(new java.awt.Color(255, 255, 255));
        dateTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(27, 20, 100));
        dateTxt.setToolTipText("Fecha");
        dateTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        dateTxt.setMinimumSize(new java.awt.Dimension(60, 32));
        dateTxt.setPreferredSize(new java.awt.Dimension(60, 32));

        nicknameLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nicknameLabel7.setForeground(new java.awt.Color(71, 18, 107));
        nicknameLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel7.setText("Mensaje");

        messageTxt.setEditable(false);
        messageTxt.setColumns(20);
        messageTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        messageTxt.setForeground(new java.awt.Color(27, 20, 100));
        messageTxt.setRows(5);
        messageTxt.setToolTipText("Mensaje");
        messageTxt.setWrapStyleWord(true);
        messageTxt.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(messageTxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(remitentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nicknameLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(destinataryIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nicknameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(moneyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nicknameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nicknameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remitentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinataryIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(nicknameLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField destinataryIdTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea messageTxt;
    private javax.swing.JTextField moneyTxt;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel nicknameLabel4;
    private javax.swing.JLabel nicknameLabel5;
    private javax.swing.JLabel nicknameLabel6;
    private javax.swing.JLabel nicknameLabel7;
    private javax.swing.JTextField remitentIdTxt;
    // End of variables declaration//GEN-END:variables
}
