/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.includes;

import model.system.Transaction;

/**
 *
 * @author 57301
 */
public class TransactionCard extends javax.swing.JPanel {
private final Transaction transaction;
    /**
     * Creates new form TransactionCard
     * @param transaction
     */
    public TransactionCard(Transaction transaction) {
//        this.transactionController = transactionController;
        this.transaction = transaction;
//        this.accountController = accountController;       
        initComponents();
        
        loadData();
    }
    
     private void loadData(){
        remitentWalletIdTxt.setText(transaction.getRemitent().getID());
        destinataryWalletIdTxt.setText(transaction.getDestinatary().getID());
        moneyTxt.setText(transaction.getMoney()+"");
        dateTxt.setText(transaction.getDate()+"");
        messageTxt.setText(transaction.getMessange());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        moneyLabel = new javax.swing.JLabel();
        nicknameLabel = new javax.swing.JLabel();
        moneyTxt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        nicknameLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        nicknameLabel2 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        nicknameLabel3 = new javax.swing.JLabel();
        messageTxt = new javax.swing.JTextField();
        remitentWalletIdTxt = new javax.swing.JLabel();
        destinataryWalletIdTxt = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(27, 20, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        moneyLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        moneyLabel.setForeground(new java.awt.Color(102, 204, 255));
        moneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyLabel.setText("Dinero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 73, 0, 0);
        jPanel1.add(moneyLabel, gridBagConstraints);

        nicknameLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(102, 204, 255));
        nicknameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel.setText("Remitente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 73, 0, 0);
        jPanel1.add(nicknameLabel, gridBagConstraints);

        moneyTxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        moneyTxt.setForeground(new java.awt.Color(255, 255, 255));
        moneyTxt.setText("00,0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 86, 0, 0);
        jPanel1.add(moneyTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 73, 0, 0);
        jPanel1.add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 73, 0, 0);
        jPanel1.add(jSeparator3, gridBagConstraints);

        nicknameLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nicknameLabel1.setForeground(new java.awt.Color(102, 204, 255));
        nicknameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel1.setText("Destinatario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 73, 0, 0);
        jPanel1.add(nicknameLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 73, 0, 0);
        jPanel1.add(jSeparator4, gridBagConstraints);

        nicknameLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nicknameLabel2.setForeground(new java.awt.Color(102, 204, 255));
        nicknameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel2.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 73, 0, 0);
        jPanel1.add(nicknameLabel2, gridBagConstraints);

        dateTxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(255, 255, 255));
        dateTxt.setText("00,0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 86, 0, 0);
        jPanel1.add(dateTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 73, 0, 0);
        jPanel1.add(jSeparator5, gridBagConstraints);

        nicknameLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nicknameLabel3.setForeground(new java.awt.Color(102, 204, 255));
        nicknameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicknameLabel3.setText("Mensaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 73, 0, 0);
        jPanel1.add(nicknameLabel3, gridBagConstraints);

        messageTxt.setEditable(false);
        messageTxt.setBackground(new java.awt.Color(53, 42, 157));
        messageTxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        messageTxt.setForeground(new java.awt.Color(255, 255, 255));
        messageTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        messageTxt.setMinimumSize(new java.awt.Dimension(60, 32));
        messageTxt.setPreferredSize(new java.awt.Dimension(60, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 3, 16, 57);
        jPanel1.add(messageTxt, gridBagConstraints);

        remitentWalletIdTxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        remitentWalletIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        remitentWalletIdTxt.setText("00,0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 86, 0, 0);
        jPanel1.add(remitentWalletIdTxt, gridBagConstraints);

        destinataryWalletIdTxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        destinataryWalletIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        destinataryWalletIdTxt.setText("00,0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 86, 0, 0);
        jPanel1.add(destinataryWalletIdTxt, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLabel destinataryWalletIdTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField messageTxt;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel moneyTxt;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JLabel nicknameLabel1;
    private javax.swing.JLabel nicknameLabel2;
    private javax.swing.JLabel nicknameLabel3;
    private javax.swing.JLabel remitentWalletIdTxt;
    // End of variables declaration//GEN-END:variables
}
