/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layouts;

import controller.AccountController;
import javax.swing.JFrame;
import model.system.Account;
import model.system.Transaction;
import model.system.Wallet;
import view.includes.Modal;

/**
 *
 * @author sonya
 */
public class IndexView extends javax.swing.JPanel {

    private final Account account;
    private final AccountController accountController;
    private Wallet wallet;

    private final JFrame parent;

    /**
     * Creates new form indexView
     *
     * @param parent
     * @param account
     * @param accountController
     */
    public IndexView(JFrame parent, Account account, AccountController accountController) {
        this.parent = parent;
        this.account = account;
        this.accountController = accountController;

        initComponents();

        moneyLabel.setText(accountController.getSaldo(account) + "");
        
        if (account != null && account.getWallets() != null) {
            for (Wallet wallet : account.getWallets()) {
                remitentWalletCombox.addItem(wallet.getID());
            }
        }

        if (account != null && account.getWallets().getSize() > 0) {
            noWalletsLabel.setText("¡Tienes " + account.getWallets().getSize() + " carteras!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        horrizontalScrollBar = new javax.swing.JScrollBar();
        verticalScrollBar = new javax.swing.JScrollBar();
        jTextField1 = new javax.swing.JTextField();
        walletNotFoundPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sendMoneyModal = new javax.swing.JPanel();
        sendMoneyModalTitle = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        destinataryWalletLabel = new javax.swing.JLabel();
        distinataryWalletTxt = new javax.swing.JTextField();
        remitentWalletLabel = new javax.swing.JLabel();
        remitentWalletCombox = new javax.swing.JComboBox<>();
        sendMoneyModalMoneyLabel = new javax.swing.JLabel();
        sendMoneyModalBtn = new javax.swing.JButton();
        sendMoneyModalMoneyLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxt = new javax.swing.JTextArea();
        moneyTxt = new javax.swing.JSpinner();
        sendMoneyPanel1 = new javax.swing.JPanel();
        walletIdLabel1 = new javax.swing.JLabel();
        walletIdTxt1 = new javax.swing.JTextField();
        searchWalletBtn1 = new javax.swing.JButton();
        sendMoneyPanel2 = new javax.swing.JPanel();
        walletIdLabel2 = new javax.swing.JLabel();
        walletIdTxt2 = new javax.swing.JTextField();
        searchWalletBtn2 = new javax.swing.JButton();
        poorMoneyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        transactionSuccesfull = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transactionFailPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        dineroDisponiblePanel = new javax.swing.JPanel();
        disponibleLabel = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        sendMoneyPanel = new javax.swing.JPanel();
        walletIdLabel = new javax.swing.JLabel();
        walletIdTxt = new javax.swing.JTextField();
        searchWalletBtn = new javax.swing.JButton();
        walletIdLabel3 = new javax.swing.JLabel();
        walletPanel = new javax.swing.JPanel();
        walletScrollPanel = new javax.swing.JScrollPane();
        walletsContaiiner = new javax.swing.JPanel();
        noWalletsLabel = new javax.swing.JLabel();
        sendMoneyPanel3 = new javax.swing.JPanel();
        walletIdLabel4 = new javax.swing.JLabel();
        walletIdHistory = new javax.swing.JTextField();
        walletIdLabel5 = new javax.swing.JLabel();
        searchForHistory = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        bodyScrollPanel = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        graphPanel = new javax.swing.JPanel();
        activityPanel = new javax.swing.JPanel();

        horrizontalScrollBar.setBackground(new java.awt.Color(53, 42, 157));
        horrizontalScrollBar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        horrizontalScrollBar.setForeground(new java.awt.Color(236, 0, 140));
        horrizontalScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        horrizontalScrollBar.setAutoscrolls(true);
        horrizontalScrollBar.setFocusable(false);
        horrizontalScrollBar.setOpaque(false);

        verticalScrollBar.setBackground(new java.awt.Color(53, 42, 157));
        verticalScrollBar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        verticalScrollBar.setForeground(new java.awt.Color(236, 0, 140));
        verticalScrollBar.setAutoscrolls(true);
        verticalScrollBar.setFocusable(false);
        verticalScrollBar.setOpaque(false);

        jTextField1.setText("jTextField1");

        walletNotFoundPanel.setBackground(new java.awt.Color(27, 20, 100));
        walletNotFoundPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        walletNotFoundPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        walletNotFoundPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        walletNotFoundPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        walletNotFoundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wallet no encontrada");
        walletNotFoundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 20));

        sendMoneyModal.setBackground(new java.awt.Color(27, 20, 100));
        sendMoneyModal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        sendMoneyModal.setLayout(new java.awt.GridBagLayout());

        sendMoneyModalTitle.setBackground(new java.awt.Color(102, 204, 255));
        sendMoneyModalTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyModalTitle.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Enviar dinero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModalTitle.add(title, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(sendMoneyModalTitle, gridBagConstraints);

        destinataryWalletLabel.setBackground(new java.awt.Color(255, 255, 255));
        destinataryWalletLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        destinataryWalletLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinataryWalletLabel.setText("Wallet Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(destinataryWalletLabel, gridBagConstraints);

        distinataryWalletTxt.setBackground(new java.awt.Color(53, 42, 157));
        distinataryWalletTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        distinataryWalletTxt.setForeground(new java.awt.Color(255, 255, 255));
        distinataryWalletTxt.setToolTipText("Nombre de usuario");
        distinataryWalletTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        distinataryWalletTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        distinataryWalletTxt.setEnabled(false);
        distinataryWalletTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        distinataryWalletTxt.setName(""); // NOI18N
        distinataryWalletTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        distinataryWalletTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(distinataryWalletTxt, gridBagConstraints);

        remitentWalletLabel.setBackground(new java.awt.Color(255, 255, 255));
        remitentWalletLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        remitentWalletLabel.setForeground(new java.awt.Color(255, 255, 255));
        remitentWalletLabel.setText("Mi wallet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(remitentWalletLabel, gridBagConstraints);

        remitentWalletCombox.setBackground(new java.awt.Color(53, 42, 157));
        remitentWalletCombox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        remitentWalletCombox.setForeground(new java.awt.Color(255, 255, 255));
        remitentWalletCombox.setPreferredSize(new java.awt.Dimension(170, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(remitentWalletCombox, gridBagConstraints);

        sendMoneyModalMoneyLabel.setBackground(new java.awt.Color(255, 255, 255));
        sendMoneyModalMoneyLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sendMoneyModalMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        sendMoneyModalMoneyLabel.setText("Mensaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(sendMoneyModalMoneyLabel, gridBagConstraints);

        sendMoneyModalBtn.setBackground(new java.awt.Color(236, 0, 140));
        sendMoneyModalBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sendMoneyModalBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendMoneyModalBtn.setText("Enviar");
        sendMoneyModalBtn.setToolTipText("Ingresar");
        sendMoneyModalBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyModalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendMoneyModalBtn.setFocusPainted(false);
        sendMoneyModalBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        sendMoneyModalBtn.setMaximumSize(new java.awt.Dimension(150, 35));
        sendMoneyModalBtn.setMinimumSize(new java.awt.Dimension(150, 35));
        sendMoneyModalBtn.setPreferredSize(new java.awt.Dimension(150, 35));
        sendMoneyModalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMoneyModalBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(sendMoneyModalBtn, gridBagConstraints);

        sendMoneyModalMoneyLabel1.setBackground(new java.awt.Color(255, 255, 255));
        sendMoneyModalMoneyLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sendMoneyModalMoneyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        sendMoneyModalMoneyLabel1.setText("Dinero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(sendMoneyModalMoneyLabel1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 100));

        messageTxt.setColumns(20);
        messageTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        messageTxt.setForeground(new java.awt.Color(27, 20, 100));
        messageTxt.setLineWrap(true);
        messageTxt.setRows(5);
        messageTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane1.setViewportView(messageTxt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(jScrollPane1, gridBagConstraints);

        moneyTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        moneyTxt.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        sendMoneyModal.add(moneyTxt, gridBagConstraints);

        sendMoneyPanel1.setBackground(new java.awt.Color(236, 0, 140));
        sendMoneyPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyPanel1.setMinimumSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel1.setPreferredSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel1.setLayout(new java.awt.GridBagLayout());

        walletIdLabel1.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdLabel1.setForeground(new java.awt.Color(255, 255, 255));
        walletIdLabel1.setText("Wallet id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 10);
        sendMoneyPanel1.add(walletIdLabel1, gridBagConstraints);

        walletIdTxt1.setBackground(new java.awt.Color(255, 45, 169));
        walletIdTxt1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdTxt1.setForeground(new java.awt.Color(255, 255, 255));
        walletIdTxt1.setToolTipText("Nombre de usuario");
        walletIdTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 45, 169), 5, true));
        walletIdTxt1.setCaretColor(new java.awt.Color(27, 20, 100));
        walletIdTxt1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        walletIdTxt1.setName(""); // NOI18N
        walletIdTxt1.setPreferredSize(new java.awt.Dimension(170, 33));
        walletIdTxt1.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        sendMoneyPanel1.add(walletIdTxt1, gridBagConstraints);

        searchWalletBtn1.setBackground(new java.awt.Color(102, 204, 255));
        searchWalletBtn1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchWalletBtn1.setForeground(new java.awt.Color(27, 20, 100));
        searchWalletBtn1.setText("buscar");
        searchWalletBtn1.setToolTipText("Ingresar");
        searchWalletBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 1, true));
        searchWalletBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchWalletBtn1.setFocusPainted(false);
        searchWalletBtn1.setMargin(new java.awt.Insets(4, 14, 4, 14));
        searchWalletBtn1.setMaximumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn1.setMinimumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn1.setPreferredSize(new java.awt.Dimension(70, 35));
        searchWalletBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWalletBtn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        sendMoneyPanel1.add(searchWalletBtn1, gridBagConstraints);

        sendMoneyPanel2.setBackground(new java.awt.Color(236, 0, 140));
        sendMoneyPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyPanel2.setMinimumSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel2.setPreferredSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel2.setLayout(new java.awt.GridBagLayout());

        walletIdLabel2.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdLabel2.setForeground(new java.awt.Color(255, 255, 255));
        walletIdLabel2.setText("Wallet id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 10);
        sendMoneyPanel2.add(walletIdLabel2, gridBagConstraints);

        walletIdTxt2.setBackground(new java.awt.Color(255, 45, 169));
        walletIdTxt2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdTxt2.setForeground(new java.awt.Color(255, 255, 255));
        walletIdTxt2.setToolTipText("Nombre de usuario");
        walletIdTxt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 45, 169), 5, true));
        walletIdTxt2.setCaretColor(new java.awt.Color(27, 20, 100));
        walletIdTxt2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        walletIdTxt2.setName(""); // NOI18N
        walletIdTxt2.setPreferredSize(new java.awt.Dimension(170, 33));
        walletIdTxt2.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        sendMoneyPanel2.add(walletIdTxt2, gridBagConstraints);

        searchWalletBtn2.setBackground(new java.awt.Color(102, 204, 255));
        searchWalletBtn2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchWalletBtn2.setForeground(new java.awt.Color(27, 20, 100));
        searchWalletBtn2.setText("buscar");
        searchWalletBtn2.setToolTipText("Ingresar");
        searchWalletBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 1, true));
        searchWalletBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchWalletBtn2.setFocusPainted(false);
        searchWalletBtn2.setMargin(new java.awt.Insets(4, 14, 4, 14));
        searchWalletBtn2.setMaximumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn2.setMinimumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn2.setPreferredSize(new java.awt.Dimension(70, 35));
        searchWalletBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWalletBtn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        sendMoneyPanel2.add(searchWalletBtn2, gridBagConstraints);

        poorMoneyPanel.setBackground(new java.awt.Color(27, 20, 100));
        poorMoneyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        poorMoneyPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        poorMoneyPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        poorMoneyPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        poorMoneyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Debe mandar más de $50 pesos");
        poorMoneyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 20));

        transactionSuccesfull.setBackground(new java.awt.Color(27, 20, 100));
        transactionSuccesfull.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        transactionSuccesfull.setMaximumSize(new java.awt.Dimension(300, 100));
        transactionSuccesfull.setMinimumSize(new java.awt.Dimension(300, 100));
        transactionSuccesfull.setPreferredSize(new java.awt.Dimension(300, 100));
        transactionSuccesfull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¡¡Transacción éxitosa!!");
        transactionSuccesfull.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 20));

        transactionFailPanel.setBackground(new java.awt.Color(27, 20, 100));
        transactionFailPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 2, true));
        transactionFailPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        transactionFailPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        transactionFailPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        transactionFailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo insuficiente");
        transactionFailPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 20));

        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(27, 20, 100));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(27, 20, 100));
        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dineroDisponiblePanel.setBackground(new java.awt.Color(27, 20, 100));
        dineroDisponiblePanel.setLayout(new javax.swing.BoxLayout(dineroDisponiblePanel, javax.swing.BoxLayout.Y_AXIS));

        disponibleLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        disponibleLabel.setForeground(new java.awt.Color(255, 255, 255));
        disponibleLabel.setText("Disponible");
        dineroDisponiblePanel.add(disponibleLabel);

        moneyLabel.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        moneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        moneyLabel.setText("$ 00,0");
        dineroDisponiblePanel.add(moneyLabel);

        titlePanel.add(dineroDisponiblePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 410, 100));

        sendMoneyPanel.setBackground(new java.awt.Color(236, 0, 140));
        sendMoneyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel.setLayout(new java.awt.GridBagLayout());

        walletIdLabel.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        walletIdLabel.setText("Wallet id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 40, 0, 0);
        sendMoneyPanel.add(walletIdLabel, gridBagConstraints);

        walletIdTxt.setBackground(new java.awt.Color(255, 45, 169));
        walletIdTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdTxt.setForeground(new java.awt.Color(255, 255, 255));
        walletIdTxt.setToolTipText("Nombre de usuario");
        walletIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 45, 169), 5, true));
        walletIdTxt.setCaretColor(new java.awt.Color(27, 20, 100));
        walletIdTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        walletIdTxt.setName(""); // NOI18N
        walletIdTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        walletIdTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 10);
        sendMoneyPanel.add(walletIdTxt, gridBagConstraints);

        searchWalletBtn.setBackground(new java.awt.Color(102, 204, 255));
        searchWalletBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchWalletBtn.setForeground(new java.awt.Color(27, 20, 100));
        searchWalletBtn.setText("Buscar");
        searchWalletBtn.setToolTipText("Ingresar");
        searchWalletBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 1, true));
        searchWalletBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchWalletBtn.setFocusPainted(false);
        searchWalletBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        searchWalletBtn.setMaximumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn.setMinimumSize(new java.awt.Dimension(70, 35));
        searchWalletBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        searchWalletBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWalletBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 0);
        sendMoneyPanel.add(searchWalletBtn, gridBagConstraints);

        walletIdLabel3.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        walletIdLabel3.setText("¡Envia dinero!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 0);
        sendMoneyPanel.add(walletIdLabel3, gridBagConstraints);

        titlePanel.add(sendMoneyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 140));

        Header.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        walletPanel.setBackground(new java.awt.Color(27, 20, 100));
        walletPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        walletPanel.setMinimumSize(new java.awt.Dimension(400, 200));
        walletPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        walletScrollPanel.setBackground(new java.awt.Color(27, 20, 100));
        walletScrollPanel.setBorder(null);
        walletScrollPanel.setAutoscrolls(true);
        walletScrollPanel.setHorizontalScrollBar(horrizontalScrollBar);

        walletsContaiiner.setBackground(new java.awt.Color(27, 20, 100));
        walletsContaiiner.setLayout(null);

        noWalletsLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        noWalletsLabel.setForeground(new java.awt.Color(255, 255, 255));
        noWalletsLabel.setText("¡No tienes carteras¡");
        walletsContaiiner.add(noWalletsLabel);
        noWalletsLabel.setBounds(0, 17, 146, 23);

        sendMoneyPanel3.setBackground(new java.awt.Color(236, 0, 140));
        sendMoneyPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        sendMoneyPanel3.setMinimumSize(new java.awt.Dimension(300, 100));
        sendMoneyPanel3.setLayout(new java.awt.GridBagLayout());

        walletIdLabel4.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdLabel4.setForeground(new java.awt.Color(255, 255, 255));
        walletIdLabel4.setText("Wallet id");
        walletIdLabel4.setAutoscrolls(true);
        walletIdLabel4.setName(""); // NOI18N
        walletIdLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 40, 0, 0);
        sendMoneyPanel3.add(walletIdLabel4, gridBagConstraints);

        walletIdHistory.setBackground(new java.awt.Color(255, 45, 169));
        walletIdHistory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletIdHistory.setForeground(new java.awt.Color(255, 255, 255));
        walletIdHistory.setToolTipText("Nombre de usuario");
        walletIdHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 45, 169), 5, true));
        walletIdHistory.setCaretColor(new java.awt.Color(27, 20, 100));
        walletIdHistory.setMargin(new java.awt.Insets(5, 5, 5, 5));
        walletIdHistory.setName(""); // NOI18N
        walletIdHistory.setPreferredSize(new java.awt.Dimension(170, 33));
        walletIdHistory.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 10, 0, 20);
        sendMoneyPanel3.add(walletIdHistory, gridBagConstraints);

        walletIdLabel5.setBackground(new java.awt.Color(255, 255, 255));
        walletIdLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        walletIdLabel5.setText("Historial específico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 0);
        sendMoneyPanel3.add(walletIdLabel5, gridBagConstraints);

        searchForHistory.setBackground(new java.awt.Color(102, 204, 255));
        searchForHistory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchForHistory.setForeground(new java.awt.Color(27, 20, 100));
        searchForHistory.setText("Buscar");
        searchForHistory.setToolTipText("Ingresar");
        searchForHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 0, 140), 1, true));
        searchForHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchForHistory.setFocusPainted(false);
        searchForHistory.setMargin(new java.awt.Insets(4, 14, 4, 14));
        searchForHistory.setMaximumSize(new java.awt.Dimension(70, 35));
        searchForHistory.setMinimumSize(new java.awt.Dimension(70, 35));
        searchForHistory.setPreferredSize(new java.awt.Dimension(70, 35));
        searchForHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForHistoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        sendMoneyPanel3.add(searchForHistory, gridBagConstraints);

        walletsContaiiner.add(sendMoneyPanel3);
        sendMoneyPanel3.setBounds(420, 10, 300, 140);

        walletScrollPanel.setViewportView(walletsContaiiner);

        javax.swing.GroupLayout walletPanelLayout = new javax.swing.GroupLayout(walletPanel);
        walletPanel.setLayout(walletPanelLayout);
        walletPanelLayout.setHorizontalGroup(
            walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, walletPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(walletScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        walletPanelLayout.setVerticalGroup(
            walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(walletScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        Header.add(walletPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 763, 208));

        add(Header, java.awt.BorderLayout.PAGE_START);

        bodyScrollPanel.setBackground(new java.awt.Color(27, 20, 100));
        bodyScrollPanel.setBorder(null);
        bodyScrollPanel.setAutoscrolls(true);
        bodyScrollPanel.setHorizontalScrollBar(horrizontalScrollBar);
        bodyScrollPanel.setVerticalScrollBar(verticalScrollBar);

        containerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        containerPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        graphPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 175, 200), 1, true));
        graphPanel.setMinimumSize(new java.awt.Dimension(200, 288));
        graphPanel.setPreferredSize(new java.awt.Dimension(200, 288));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        containerPanel.add(graphPanel);

        activityPanel.setBackground(new java.awt.Color(255, 255, 255));
        activityPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 175, 200), 1, true));
        activityPanel.setMinimumSize(new java.awt.Dimension(200, 288));
        activityPanel.setPreferredSize(new java.awt.Dimension(200, 288));

        javax.swing.GroupLayout activityPanelLayout = new javax.swing.GroupLayout(activityPanel);
        activityPanel.setLayout(activityPanelLayout);
        activityPanelLayout.setHorizontalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        activityPanelLayout.setVerticalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        containerPanel.add(activityPanel);

        bodyScrollPanel.setViewportView(containerPanel);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchWalletBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWalletBtnActionPerformed
        wallet = accountController.getWallet(walletIdTxt.getText());

        if (wallet == null) {
            Modal modal = new Modal(parent, "Wallet no encontrada", true, walletNotFoundPanel);
        } else {
            distinataryWalletTxt.setText(wallet.getNickname());

            if (account != null && account.getWallets() != null) {
                for (Wallet wallet : account.getWallets()) {
                    remitentWalletCombox.addItem(wallet.getID());
                }
            }
            Modal modal = new Modal(parent, "Enviar dinero", true, sendMoneyModal);
        }
    }//GEN-LAST:event_searchWalletBtnActionPerformed

    private void searchWalletBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWalletBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchWalletBtn1ActionPerformed

    private void searchWalletBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWalletBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchWalletBtn2ActionPerformed

    private void searchForHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForHistoryActionPerformed
        wallet = accountController.getWallet(walletIdHistory.getText());
        if (wallet != null) {
            System.out.println(accountController.getHistorial(wallet));
        } else {
            Modal modal = new Modal(parent, "Wallet no encontrada", true, walletNotFoundPanel);
        }
    }//GEN-LAST:event_searchForHistoryActionPerformed

    private void sendMoneyModalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMoneyModalBtnActionPerformed
        
        String walletId = (String) remitentWalletCombox.getSelectedItem();
        Wallet remitent = accountController.getWallet(walletId);
        Double money = Double.parseDouble(moneyTxt.getValue().toString());
        System.out.println(IndexView.class.getName() + " MENSAJE " + remitent.getID() + " - " + wallet.getID() + " - " + money);
        Transaction transaction = new Transaction(remitent, wallet, money, messageTxt.getText());
        
        if (accountController.getTransactionController().add(transaction) == 0) {
        
            Modal modal = new Modal(parent, "Transacción éxitosa", true, transactionSuccesfull);
            transaction.getRemitent().setMoney(transaction.getRemitent().getMoney() - transaction.getMoney());
            transaction.getDestinatary().setMoney(transaction.getDestinatary().getMoney() + transaction.getMoney());
            double moneyTemp = Double.parseDouble(moneyLabel.getText()) - transaction.getMoney();
            moneyLabel.setText(moneyTemp + "");
            
            this.removeAll();
        } else {
            Modal modal = new Modal(parent, "Transacción errada", true, transactionFailPanel);
        }

    }//GEN-LAST:event_sendMoneyModalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel activityPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JScrollPane bodyScrollPanel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel destinataryWalletLabel;
    private javax.swing.JPanel dineroDisponiblePanel;
    private javax.swing.JLabel disponibleLabel;
    private javax.swing.JTextField distinataryWalletTxt;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollBar horrizontalScrollBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea messageTxt;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JSpinner moneyTxt;
    public javax.swing.JLabel noWalletsLabel;
    private javax.swing.JPanel poorMoneyPanel;
    private javax.swing.JComboBox<String> remitentWalletCombox;
    private javax.swing.JLabel remitentWalletLabel;
    private javax.swing.JButton searchForHistory;
    private javax.swing.JButton searchWalletBtn;
    private javax.swing.JButton searchWalletBtn1;
    private javax.swing.JButton searchWalletBtn2;
    private javax.swing.JPanel sendMoneyModal;
    private javax.swing.JButton sendMoneyModalBtn;
    private javax.swing.JLabel sendMoneyModalMoneyLabel;
    private javax.swing.JLabel sendMoneyModalMoneyLabel1;
    private javax.swing.JPanel sendMoneyModalTitle;
    private javax.swing.JPanel sendMoneyPanel;
    private javax.swing.JPanel sendMoneyPanel1;
    private javax.swing.JPanel sendMoneyPanel2;
    private javax.swing.JPanel sendMoneyPanel3;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel transactionFailPanel;
    private javax.swing.JPanel transactionSuccesfull;
    private javax.swing.JScrollBar verticalScrollBar;
    private javax.swing.JTextField walletIdHistory;
    private javax.swing.JLabel walletIdLabel;
    private javax.swing.JLabel walletIdLabel1;
    private javax.swing.JLabel walletIdLabel2;
    private javax.swing.JLabel walletIdLabel3;
    private javax.swing.JLabel walletIdLabel4;
    private javax.swing.JLabel walletIdLabel5;
    private javax.swing.JTextField walletIdTxt;
    private javax.swing.JTextField walletIdTxt1;
    private javax.swing.JTextField walletIdTxt2;
    private javax.swing.JPanel walletNotFoundPanel;
    private javax.swing.JPanel walletPanel;
    private javax.swing.JScrollPane walletScrollPanel;
    private javax.swing.JPanel walletsContaiiner;
    // End of variables declaration//GEN-END:variables
}
