/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layouts;

import model.system.Account;
/**
 *
 * @author sonya
 */
public class ProfileView extends javax.swing.JPanel {
    
    private Account account;
    
    /**
     * Creates new form profileView
     * @param account
     */
    public ProfileView(Account account) {
        this.account = account;
        
        initComponents();
        
        loadData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bodyPanel = new javax.swing.JPanel();
        accountDataPanel = new javax.swing.JPanel();
        accountNameLabel = new javax.swing.JLabel();
        idUser = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();

        setLayout(new java.awt.BorderLayout());

        bodyPanel.setBackground(new java.awt.Color(27, 20, 100));
        bodyPanel.setLayout(new java.awt.GridBagLayout());

        accountDataPanel.setBackground(new java.awt.Color(102, 204, 255));
        accountDataPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 20, 100), 1, true));
        accountDataPanel.setLayout(new java.awt.GridBagLayout());

        accountNameLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        accountNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountNameLabel.setText("Tu cuenta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        accountDataPanel.add(accountNameLabel, gridBagConstraints);

        idUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idUser.setForeground(new java.awt.Color(255, 255, 255));
        idUser.setText("id del usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        accountDataPanel.add(idUser, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bodyPanel.add(accountDataPanel, gridBagConstraints);

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bodyPanel.add(userLabel, gridBagConstraints);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bodyPanel.add(passwordLabel, gridBagConstraints);

        userTxt.setBackground(new java.awt.Color(53, 42, 157));
        userTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 255, 255));
        userTxt.setToolTipText("Nombre de usuario");
        userTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        userTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        userTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        userTxt.setName(""); // NOI18N
        userTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        userTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bodyPanel.add(userTxt, gridBagConstraints);

        passwordTxt.setEditable(false);
        passwordTxt.setBackground(new java.awt.Color(53, 42, 157));
        passwordTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setToolTipText("Contreña");
        passwordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 42, 157), 5, true));
        passwordTxt.setCaretColor(new java.awt.Color(236, 0, 140));
        passwordTxt.setMargin(new java.awt.Insets(5, 5, 5, 5));
        passwordTxt.setMinimumSize(new java.awt.Dimension(170, 33));
        passwordTxt.setPreferredSize(new java.awt.Dimension(170, 33));
        passwordTxt.setSelectionColor(new java.awt.Color(236, 0, 140));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bodyPanel.add(passwordTxt, gridBagConstraints);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        this.idUser.setText("Id: " + account.getID());
        userTxt.setText(account.getUserName());
        passwordTxt.setText(account.getPassword());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountDataPanel;
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
