/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layouts;

import controller.AccountController;
import java.awt.Dimension;
import javax.swing.JFrame;
import model.list.List;
import model.system.Account;
import model.system.Transaction;
import model.system.Wallet;
import view.includes.Modal;
import view.includes.TransactionCard;
import view.includes.WrapLayout;


/**
 *
 * @author sonya
 */
public class TransactionInformationView extends javax.swing.JPanel {

    private final Account account;
    private final JFrame parent;
    private final AccountController accountController;

    /**
     * Creates new form TransactionInformationView
     *
     * @param account
     * @param accountController
     * @param parent
     */
    public TransactionInformationView(Account account, AccountController accountController, JFrame parent) {
        this.account = account;
        this.accountController = accountController;
        this.parent = parent;
        initComponents();
        updateWalletsUser();
    }

    /**
     *
     * @param transactions
     */
    private void loadTransactions(List<Transaction> transactions) {
        transactionsPanel.removeAll();
        
        for (Transaction transaction : transactions) {
            transactionsPanel.add(new TransactionCard(transaction));
        }

        transactionsPanel.validate();
        transactionsPanel.repaint();
    }

    public void updateWalletsUser() {
        for (Wallet wallet : account.getWallets()) {
            if (!existOnCombox(wallet)) {
                walletsUserCombox.addItem(wallet.getID());
            }
        }
    }

    /**
     * Método para que no se estén agregando las carteras después de que ya
     * están en el Combox
     *
     * @param wallet
     * @return
     */
    private boolean existOnCombox(Wallet wallet) {
        for (int i = 0; i < walletsUserCombox.getItemCount(); i++) {
            if (wallet.getID().equals(walletsUserCombox.getItemAt(i))) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        transactionWalletNotFoundPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        transactionByIdBtn = new javax.swing.JButton();
        walletsUserCombox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        transactionScroll = new javax.swing.JScrollPane();
        transactionsPanel = new javax.swing.JPanel();

        transactionWalletNotFoundPanel.setBackground(new java.awt.Color(255, 255, 255));
        transactionWalletNotFoundPanel.setMaximumSize(new java.awt.Dimension(281, 92));
        transactionWalletNotFoundPanel.setMinimumSize(new java.awt.Dimension(281, 92));
        transactionWalletNotFoundPanel.setPreferredSize(new java.awt.Dimension(281, 92));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("¡¡No se encontraron transacctiones en las que");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText(" participe esta billetera!!");

        javax.swing.GroupLayout transactionWalletNotFoundPanelLayout = new javax.swing.GroupLayout(transactionWalletNotFoundPanel);
        transactionWalletNotFoundPanel.setLayout(transactionWalletNotFoundPanelLayout);
        transactionWalletNotFoundPanelLayout.setHorizontalGroup(
            transactionWalletNotFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionWalletNotFoundPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionWalletNotFoundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        transactionWalletNotFoundPanelLayout.setVerticalGroup(
            transactionWalletNotFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionWalletNotFoundPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(71, 18, 107));
        headerPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id de la billetera");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 242, 0, 0);
        headerPanel.add(jLabel2, gridBagConstraints);

        transactionByIdBtn.setBackground(new java.awt.Color(216, 49, 91));
        transactionByIdBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        transactionByIdBtn.setForeground(new java.awt.Color(255, 255, 255));
        transactionByIdBtn.setText("Buscar");
        transactionByIdBtn.setBorderPainted(false);
        transactionByIdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionByIdBtn.setFocusPainted(false);
        transactionByIdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionByIdBtnMouseClicked(evt);
            }
        });
        transactionByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionByIdBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 0);
        headerPanel.add(transactionByIdBtn, gridBagConstraints);

        walletsUserCombox.setBackground(new java.awt.Color(151, 58, 168));
        walletsUserCombox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        walletsUserCombox.setForeground(new java.awt.Color(255, 255, 255));
        walletsUserCombox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        walletsUserCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletsUserComboxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        headerPanel.add(walletsUserCombox, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 209, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mis Transacciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 693;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        headerPanel.add(jLabel6, gridBagConstraints);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.BorderLayout());

        transactionScroll.setBackground(new java.awt.Color(255, 255, 255));
        transactionScroll.setBorder(null);

        transactionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        transactionsPanel.setAutoscrolls(true);
        transactionsPanel.setMaximumSize(new java.awt.Dimension(50, 50));
        transactionsPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        transactionsPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        transactionsPanel.setLayout(new javax.swing.OverlayLayout(transactionsPanel));
        transactionScroll.setViewportView(transactionsPanel);

        bodyPanel.add(transactionScroll, java.awt.BorderLayout.CENTER);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void transactionByIdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionByIdBtnMouseClicked

        Wallet wallet = accountController.getWalletById((String) walletsUserCombox.getSelectedItem());
        List<Transaction> transactionByWallet = accountController.getHistorial(wallet);
        if (transactionByWallet.getSize() != 0) {
            loadTransactions(transactionByWallet);
        } else {
            Modal modal = new Modal(parent, "Sin transacciones", true, transactionWalletNotFoundPanel);
        }

    }//GEN-LAST:event_transactionByIdBtnMouseClicked

    private void transactionByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionByIdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionByIdBtnActionPerformed

    private void walletsUserComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletsUserComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walletsUserComboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton transactionByIdBtn;
    private javax.swing.JScrollPane transactionScroll;
    private javax.swing.JPanel transactionWalletNotFoundPanel;
    private javax.swing.JPanel transactionsPanel;
    private javax.swing.JComboBox<String> walletsUserCombox;
    // End of variables declaration//GEN-END:variables
}
