
package view.arbolGrafico;

import model.structure.nodo.NodoArbol;
import model.system.Bloque;
import model.system.Transaccion;

public class BloqueNodo extends javax.swing.JPanel {

    /**
     * Creates new form BloqueNodo
     */
    public BloqueNodo(NodoArbol bloque) {
        initComponents();
        
        System.out.println("view.arbolGrafico.BloqueNodo nuevo");
        Transaccion t;
        int i = 0;
        while (i <= ((Bloque) bloque.getInfo()).getTransaccionesAct()) {
            NodoArbol p = bloque.getChildren().search(i);
            
            if (p != null) {
                t = (Transaccion) p.getInfo();
                this.add(new TransaccionNodo(t));
            }
            i++;
            System.out.println("view.arbolGrafico.BloqueNodo " + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(236, 0, 140));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
